### ISSUE TITLE
Serve app at subfolder?

### ISSUE THREAD

**Issue by hongquan** [kitbagjs/router#245]
For example, we want our Vue app to run at `/p/` URL. In `vue-router`, we achieve that by [`createWebHistory`](https://router.vuejs.org/api/#createWebHistory), but in `@kitbag/router`, I haven't found an equivalent.

**Comment by stackoverfloweth** [comment]
@hongquan, I think this is a good suggestion since the pattern is commonly used.

However, I also think we can solve for your use case rather simply unless I'm missing something that `base` option does in vue-router.

If you simply create a base route that acts as the parent to whatever base routes you currently have, this should achieve the same end goal.

```ts
// this route won't be navigable, will use `<RouterView />` as component by deafult
const baseRoute = createRoute({
  path: "/p/"
})

// routes supplied to router does not need to include `baseRoute` for this to work
const routes = [
  createRoute({
    parent: baseRoute,
    name: "foo",
    // actual path will be "/p/foo"
    path: "foo",
    ...
  })
] as const
```

**Comment by hongquan** [comment]
@stackoverfloweth Thanks.
