### ISSUE TITLE
Make route writable for params

### ISSUE THREAD

**Issue by stackoverfloweth** [kitbagjs/router#81]
With regard to path params, our docs say that a route like `/users/:id`

> ...these params are reactive strings. If you update a param, the url will be updated accordingly.

At the time of writing this issue that's not true, `router.route` is `DeepReadonly`. So before going live, we'll need to reconcile this difference.

**Comment by pleek91** [comment]
@stackoverfloweth I'm going to use this issue to write down some thoughts around this and explore some syntax. I'm not advocating for any of these ideas. Just working out thoughts. Maybe something here will resonate with you or spark and idea.

Problem: Updating params should feel like updating state and less like routing. Binding a param from a route (like a search term, page number, etc) to some ux is common and we'd like at least some first party support for this other than just manually calling `router.push` or `router.replace`. 

## Reactive params object
It would be really nice in some use cases to just bind directly to a param on the route like this.
```vue
<input v-model="route.params.page" type="number" step="1">
```

However changing that example slightly drastically changes the use case. Users probably don't want every `update:modelValue` event to trigger a route push. 
```vue
<input v-model="route.params.search" type="text">
```

There also the problem of updating multiple params at once. This could be quite common, but how do we know if this should trigger two route updates or just one?
```ts
function update() {
  route.params.entity = 'user'
  route.params.id = 'pleek91'
}
```

One possible solution to these is to debounce by default. If multiple param updates happens simultaneously, collect them all and then trigger a single route update. However the debounce necessary for v-modeling text is at least 500ms which IMO is to long for a default. Which kind of eliminates this in my mind other than maybe "nextTick" type debounce to account for the `update()` example. 

I think if we go this route we should give users the ability to configure whether updating a param is a push or a replace action. I'd probably default to `replace`. 

## Route patching
It would be convenient to provide a syntax for patching the current route's params. Something that is a shortcut for effectively calling push but with the same route key. This solves the update function issue where multiple params need to be changed at once. 
```ts
// set multiple values at once
route.update({
  entity: 'user',
  id: 'pleek91',
}, { replace: true })

// set an individual value
route.update('user', 'pleek91', { replace: true })
```

## Param debouncing
It might be nice to offer a built in way of debouncing updates to an individual param. 
```ts
const search = route.paramRef('search', { debounce: 1000 })
```
```vue
<input v-model="search" type="text">
```
This also might be better left to userland implementation to avoid having to support this long term. 

## Param freezing
Tangentially related is a complaint I've always had with reactive params. When the route changes, and a component is about to be unmounted, sometimes the params can change BEFORE the component is unmounted. And cause random errors to happen immediately before the component is torn down. I'd love to solve this somehow can cause components that are not part of the "to" to get their route frozen so that it doesn't change and then then get removed. 

I'm not sure if we can solve this problem though (or even if we should).

**Comment by stackoverfloweth** [comment]
moving to Notion
https://www.notion.so/Editable-Params-2e359e1153b24400b86b48315edd9fe6
